[package]
name = "tcf-parser-rs"
version = "0.0.1"
authors = ["Mingxin <zou.mingxin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6.0.0-alpha1"
base64 = "0.12"
chrono = "0.4.13"